### ISSUE TITLE
自己的梯子不管用

### ISSUE THREAD

**Issue by Rain-0x01-39** [xiaoming-ssr/FanQiang-Book#6]
服务器都搭建完成了，但是仍然无法访问Ǥőøǥłę
系统代理设置为PAC模式了
![image](https://github.com/xiaoming-ssr/FanQiang-Book/assets/83620631/8e4cfff7-d2a7-4ec9-96ef-dd1bac2f62ad)

**Comment by BeAtruer** [comment]
请问你怎么解决的呢
